### ISSUE TITLE
Parchment build fails

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/parchment#172]
```
% git clone --recurse-submodules git@github.com:curiousdannii/parchment.git
% cd parchment
% npm install
% npm run build
```

> parchment@2025.1.0 build
> ./build.js

Building projects: tools, web
⚠ Warning: Using npm rather than upstream version of Emglken
✘ [ERROR] Could not resolve "../upstream/emglken/build/file-sizes.json"

    src/common/launcher.ts:17:31:
      17 │ import emglken_file_sizes from '../upstream/emglken/build/file-sizes.json'
         ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/dfabulich/git/parchment/node_modules/esbuild/lib/main.js:1476
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
src/common/launcher.ts:17:31: ERROR: Could not resolve "../upstream/emglken/build/file-sizes.json"
    at failureErrorWithLog (/Users/dfabulich/git/parchment/node_modules/esbuild/lib/main.js:1476:15)
    at /Users/dfabulich/git/parchment/node_modules/esbuild/lib/main.js:945:25
    at /Users/dfabulich/git/parchment/node_modules/esbuild/lib/main.js:1354:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v23.1.0
```

**Comment by dfabulich** [comment]
* I bisected it to bcf6e9c (the merge from the testing branch).
* I checked out db79b6a (the head of the testing branch at the time, the second parent of bcf6e9c) and the issue repro'd there.
* I checked out bc7db6f (ten revisions back from db79b6a) and the issue did not repro there.
* So I ran another bisect and it pointed to c227df8c

The issue appears to be in <https://github.com/curiousdannii/parchment/commit/c227df8c9d65659b760f6f5549ab5d4967df5628#diff-c6df14567645b3df070b9a8415aa7717b126c540e5b36f9940c18fd8db6ee333R17> `src/common/launcher.ts` line 17.

```
import emglken_file_sizes from '../upstream/emglken/build/file-sizes.json'
```

At each step in the bisect, I ran:

```
git clean -xdf && git submodule sync --recursive && git submodule update --init --recursive && npm i && npm run build
```

**Comment by dfabulich** [comment]
Oh, I get it. "⚠ Warning: Using npm rather than upstream version of Emglken" means that it's not building Emglken in the `upstream` directory, so we can't import it from `../upstream/emglken/build/file-sizes.json`.

I can get it to work by changing that line to `import emglken_file_sizes from 'emglken/build/file-sizes.json'` or by manually running `./build.sh` in the `emglken` directory.

**Comment by curiousdannii** [comment]
It's designed so that you can use the npm version of English rather than building it again, but it looks like I had one place which referred to the wrong path.

The command `npm run link-local-emglken` will handle switching to the local copy, but it shouldn't be necessary.
